services:
  - type: web
    name: social-hamster
    runtime: python
    buildCommand: "pip install -r requirements.txt && playwright install chromium"
    startCommand: "uvicorn backend_main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: YOUTUBE_API_KEY
        sync: false
      - key: TIKTOK_MS_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
